---
title: "Sensor Data Interpolation"
author: "Hayley Garment"
date: "5/12/2020"
output: html_document
---

In this file:



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readr)
library(lubridate)
library(tmap)
library(sf)
library(mapview)
library(tmap)
library(broom)

library(gstat) # Use gstat's idw routine
library(sp)    # Used for the spsample function
library(raster)
```

GET STATIONS SF
```{r}
stations <- read.csv('data/stations.csv') %>% filter(name != 'Urgakh naran')

sf_stations <- st_as_sf(stations, coords = c("lon", "lat"), crs = 4326) %>%
  st_transform(3414)

sf_stations <- st_transform(sf_stations, sf::st_crs("+proj=longlat +datum=WGS84"))

#st_write(sf_stations,'data/stations.geojson')
```

GET RASTERS FROM FRAMES
```{r}
sample <- readRDS('sample_data/sensor_data.rds') %>% filter(name != 'Urgakh naran')

date_frames <- sample %>% distinct(date)

rasters = list()

for(i in 1:nrow(date_frames)) {
  date_frame <- date_frames$date[i]
  frame_data <- sample %>% filter(date == date_frame)

  sf_frame_data <- left_join(frame_data, sf_stations) %>%
    dplyr::select(name, aqi, geometry) %>%
    st_as_sf(crs=3414)
  
  raster <- createRasterFromFrame(sf_frame_data)
  rasters[[i]] <- raster
}

rasters[[4]]

#all_rasters <- do.call(rbind, rasters) not working!

```


CREATE RASTER FROM FRAME
```{r}
createRasterFromFrame <- function(data_frame) {
  sp_sample <- data_frame %>% as_Spatial()
  
  # Create an empty grid where n is the total number of cells
  grd              <- as.data.frame(spsample(sp_sample, "regular", n=100000))
  names(grd)       <- c("X", "Y")
  coordinates(grd) <- c("X", "Y")
  gridded(grd)     <- TRUE  # Create SpatialPixel object
  fullgrid(grd)    <- TRUE  # Create SpatialGrid object
  
  proj4string(grd) <- proj4string(sp_sample)
  
  # Interpolate the grid cells using a power value of 2 (idp=2.0) #arbitrary!!
  sp_sample.idw <- gstat::idw(aqi ~ 1, sp_sample, newdata=grd, idp=2.0)
  
  # Convert to raster object
  raster_layer <- raster(sp_sample.idw)
  
  crs(raster_layer) <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0" 
  
  raster_layer
  # add time!!
}
```

TESTING
```{r}
tmap_mode("view")
  

# Plot
tm_shape(rasters[[2]]) + 
  tm_raster(n=10, palette = "YlGnBu", contrast = c(0.1, 1), alpha = 0.5)

tm_shape(rasters[[3]]) + 
  tm_raster(n=10, palette = "YlGnBu", contrast = c(0.1, 1), alpha = 0.5)
```

WRITE sAMPLE LAYER TO FILE
```{r}
writeRaster(rasters[[3]], "sample_data/sample_frame_raster.tif", format = "GTiff")
```

INSPECT RASTER LAYER
```{r}
raster_sample <- rasters[[3]]

raster_sample <- as.integer(raster_sample) # should round this TODO

writeRaster(raster_sample, "sample_data/sample_frame_raster.tif", format = "GTiff")

ras %>% as.matrix() 
# all unique valeues! how can make bands like this O.O
```

